### ISSUE TITLE
Is it possible to set pixel size?

### ISSUE THREAD

**Issue by kenkunz** [harrisj/qrencoder#5]
Hi Jacob,

Thanks for creating and sharing this! I was experimenting with it yesterday for a work project. Is there a way to set the pixel (dot) size? libqrcode seems to support this (in the qrencode command-line utility with the -s switch). But I couldn't find this option in your bindings.

Thanks!
Ken

**Comment by jgdavey** [comment]
Yes, see the documentation for the QREncoder::QRCode#png method here: http://rdoc.info/github/harrisj/qrencoder/master/QREncoder/QRCode#png-instance_method

In essence you would do something like the following:

``` ruby
QREncoder.encode("My string").png(:pixels_per_module => 5).save("path/to/file.png")
```

**Comment by kenkunz** [comment]
Sweet – thanks for the quick response!
