### ISSUE TITLE
Qrencode from Ubuntu repo

### ISSUE THREAD

**Issue by cande** [harrisj/qrencoder#9]
Is it possible to use this with ubuntus qrencode package?

**Comment by jgdavey** [comment]
Great question. I've built the package successfully on Ubuntu from source, but the gem needs the headers to be able to compile correctly. If the Ubuntu package has development headers, it should work, but YMMV. 

Anyone else have experience with this? /cc @harrisj

**Comment by cande** [comment]
Ah yes I got it working with Ubuntu with these packages:

> libqrencode-dev python-qrencode qrencode

not sure if i need the python package.
